name: Deploy website

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

env:
  BRANCH_NAME: ${{ github.ref_name }}

permissions:
  contents: read
  pull-requests: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }} # Explicitement checkout le tag

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"

      - name: Install Netlify
        run: npm install netlify-cli@18.1.0 -g

      - name: Install Dependencies
        run: npm ci

      - name: Build project
        env:
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
        run: npm run build

      - name: Deploy to Netlify
        id: netlify_deploy
        run: |
          # Déployer en production si c'est un tag                                                                                                                 
          netlify deploy \                                                                                                                                         
            --dir dist \                                                                                                                                           
            --site ${{ secrets.NETLIFY_SITE_ID }} \                                                                                                                
            --auth ${{ secrets.NETLIFY_API_TOKEN }} \                                                                                                              
            --prod \                                                                                                                                               
            > deploy_output.txt
